--// Service was made by JeffMonster7 on Roblox for Horizonix Studios
--/ Service V4.9.2 - Updated as of 14/05/2024 (UK)
local service = {};
local services = {
	AnalyticsService = game:GetService("AnalyticsService");
	AssetService = game:GetService("AssetService");
	BadgeService = game:GetService("BadgeService");
	Chat = game:GetService("Chat");
	ChatService = game:GetService("ChatService");
	CollectionService = game:GetService("CollectionService");
	ContextActionService = game:GetService("ContextActionService");
	ContentProvider = game:GetService("ContentProvider");
	DataModel = game:GetService("DataModel");
	DataStoreService = game:GetService("DataStoreService");
	Debris = game:GetService("Debris");
	GameAnalytics = game:GetService("GameAnalytics");
	GamePassService = game:GetService("GamePassService");
	GroupService = game:GetService("GroupService");
	GuiService = game:GetService("GuiService");
	HttpRbxApiService = game:GetService("HttpRbxApiService");
	HttpService = game:GetService("HttpService");
	InsertService = game:GetService("InsertService");
	Lighting = game:GetService("Lighting");
	LogService = game:GetService("LogService");
	LocalizationService = game:GetService("LocalizationService");
	MarketPlace = game:GetService("MarketPlace");
	MarketplaceService = game:GetService("MarketplaceService");
	MessagingService = game:GetService("MessagingService");
	NotificationService = game:GetService("NotificationService");
	PathfindingService = game:GetService("PathfindingService");
	PhysicsService = game:GetService("PhysicsService");
	PlayerAvatar = game:GetService("PlayerAvatar");
	Players = game:GetService("Players");
	PointsService = game:GetService("PointsService");
	PreloadService = game:GetService("PreloadService");
	PublishPlaceService = game:GetService("PublishPlaceService");
	ReplicatedStorage = game:GetService("ReplicatedStorage");
	RobloxChat = game:GetService("RobloxChat");
	RobloxChatService = game:GetService("RobloxChatService");
	RobloxContentProvider = game:GetService("RobloxContentProvider");
	RobloxCoreScript = game:GetService("RobloxCoreScript");
	RobloxDataService = game:GetService("RobloxDataService");
	RobloxGui = game:GetService("RobloxGui");
	RobloxLocalization = game:GetService("RobloxLocalization");
	RobloxLocalizationService = game:GetService("RobloxLocalizationService");
	RobloxMarketplace = game:GetService("RobloxMarketplace");
	RobloxPathfindingService = game:GetService("RobloxPathfindingService");
	RobloxPublishService = game:GetService("RobloxPublishService");
	RobloxReplicatedFirst = game:GetService("RobloxReplicatedFirst");
	RobloxReplicatedStorage = game:GetService("RobloxReplicatedStorage");
	RobloxScriptService = game:GetService("RobloxScriptService");
	RobloxSettings = game:GetService("RobloxSettings");
	RobloxSocialService = game:GetService("RobloxSocialService");
	RobloxStudio = game:GetService("RobloxStudio");
	RobloxTeams = game:GetService("RobloxTeams");
	RobloxTeleportService = game:GetService("RobloxTeleportService");
	RobloxTerrain = game:GetService("RobloxTerrain");
	RobloxTweenService = game:GetService("RobloxTweenService");
	RobloxUserInputService = game:GetService("RobloxUserInputService");
	RunService = game:GetService("RunService");
	Selection = game:GetService("Selection");
	ServerScriptService = game:GetService("ServerScriptService");
	ServerSettings = game:GetService("ServerSettings");
	ServerStorage = game:GetService("ServerStorage");
	SoundService = game:GetService("SoundService");
	StarterGui = game:GetService("StarterGui");
	StarterPack = game:GetService("StarterPack");
	StarterPlayer = game:GetService("StarterPlayer");
	StarterService = game:GetService("StarterService");
	StudioService = game:GetService("StudioService");
	TeamService = game:GetService("TeamService");
	TeleportService = game:GetService("TeleportService");
	TestService = game:GetService("TestService");
	TextFilter = game:GetService("TextFilter");
	TextService = game:GetService("TextService");
	ToolBox = game:GetService("Toolbox");
	TweenService = game:GetService("TweenService");
	UserInputService = game:GetService("UserInputService");
	VRService = game:GetService("VRService");
	WorkspaceService = game:GetService("Workspace");
	--// Extras
	CoreGui = game:WaitForChild('CoreGui');
};
function service:get(request)
	if services[request] then
		return services[request];
	else
		return 'pc:8';
	end;
end;
return service;
